<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCCXqhGD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCCXqhGD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCCXqhGD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCCXqhGD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCCXqhGD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CCXqhGD',
    'container.build_id' => '60509387',
    'container.build_time' => 1580033972,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCCXqhGD');
